### PR TITLE
Backporting changes merged to v4, also in v3

### PR DESCRIPTION
**Pull request by specialtactics**
Hi

I am back-porting these merged PRs (which were merged into v4), so that they can also be in v3 api sdk version.
https://github.com/hyperwallet/php-sdk/pull/44/files
https://github.com/hyperwallet/php-sdk/pull/23/files

Could you please accept and tag this in v1 of this SDK?

Thanks!

### CODE REVIEW

**Comment by specialtactics** [comment]
Hey @jchanghw @Rrathinasabapath just wanted to draw attention to this one.

**Review by vkorotchenko — APPROVED** [review]

**Review by arao6 — APPROVED** [review]

**Comment by specialtactics** [comment]
Thank you!

**Comment by vkorotchenko** [comment]
@specialtactics  Thank you for your patience, we also did a release on friday. Changes should now be available in 1.6.1

**Comment by specialtactics** [comment]
No problem @vkorotchenko , and thanks we're already using this new tag!

**Pull request merged**
