### PR TITLE
Add $clientOptions to constructor and pass to ApiClient object

### PR DESCRIPTION
**Pull request by andrej-griniuk**

### CODE REVIEW

**Comment by andrej-griniuk** [comment]
Any chance to get this merged or is there anything else that needs to be done?

**Comment by specialtactics** [comment]
Hey @wmews-hw any reason this hasn't been merged yet ?

**Comment by andrej-griniuk** [comment]
Not sure why the build is failing in PHP 5.6 while passing in 7.0 and HHVM. Seems unrelated to my changes.

**Comment by specialtactics** [comment]
I'd like to reference this short investigation about the failing test:
https://github.com/hyperwallet/php-sdk/pull/43

**Comment by specialtactics** [comment]
I made a PR to fix the failing test here: https://github.com/hyperwallet/php-sdk/pull/44

Please merge that PR, and then you can merge this. Although this PR doesn't cause any tests to fail anyway.

**Comment by specialtactics** [comment]
@Rrathinasabapath  could you please look at this? It's been open for about one and a half years now.

**Review by pmoravek-hw — APPROVED** [review]

**Review by peter-joseph — APPROVED** [review]

**Pull request merged**
